### ISSUE TITLE
Reuse upstream ocropy?

### ISSUE THREAD

**Issue by kba** [syedsaqibbukhari/docanalysis#1]
The ocropus folder is a copy of the ocrolib folder of [tmbdev/ocropy](https://github.com/tmbdev/ocropy) ca. 2016.

Is there a reason for not using upstream ocropy?

**Comment by kba** [comment]
Fixed in 0779f6a

**Comment by kba** [comment]
But it's not yet merged in master!

**Comment by n00blet** [comment]
It will be merged in the master soon, we were waiting for the confirmation from your side.

**Comment by kba** [comment]
No, sorry I meant the `merger` branch, not `master`. But the change is there, I was just confused because much of what's in `merger` was in the 30 commits in #13.
