### ISSUE TITLE
Model is offline

### ISSUE THREAD

**Issue by kba** [syedsaqibbukhari/docanalysis#17]
https://cloud.dfki.de/owncloud/index.php/s/GZ6zZtyF6yDPbwm throws 404

**Comment by mjenckel** [comment]
please use https://cloud.dfki.de/owncloud/index.php/s/3zKza5sRfQB3ygy for now
we will update the README with the next commit

**Comment by n00blet** [comment]
The model link has been updated for now in the 'merger' branch.
We will rewrite some parts of the README in the next commit.
