### ISSUE TITLE
READMEs should not be in subfolders

### ISSUE THREAD

**Issue by kba** [syedsaqibbukhari/docanalysis#18]
The README_*.md files have been moved to `ocrd_anybaseocr/cli`. Why? Like this, they won't be found (links in root README.md).

Why even multiple README, why not have that information in one place?

**Comment by n00blet** [comment]
Okay, thanks for the comment. We will update it and have a single README for the entire project.

**Comment by n00blet** [comment]
README's have been moved from subfolders in e502d94ed3d9419649388809190c2df5913c9fea
