### ISSUE TITLE
Split off / move samples to OCR-D/assets?

### ISSUE THREAD

**Issue by kba** [syedsaqibbukhari/docanalysis#2]
To make your test data reusable and algorithms comparable, it would be useful to have your samples in our [OCR-D/assets](https://github.com/OCR-D/assets) repository instead of here.

This had the additional advantage of reducing repository size.

**Comment by cneud** [comment]
TODO: add https://github.com/syedsaqibbukhari/docanalysis/blob/master/samples/becker_quaestio_1586_00013.tif to https://github.com/OCR-D/assets and use it from there.

**Comment by mmreza79** [comment]
Thank you for your guidelines but I am not able to upload sample tif file to https://github.com/OCR-D/assets. I need push access to this repository, is not it?

**Comment by kba** [comment]
Have a look at https://github.com/OCR-D/assets/pull/20
