### ISSUE TITLE
Checking in pix2pixHD breaks the licensing

### ISSUE THREAD

**Issue by kba** [syedsaqibbukhari/docanalysis#20]
If `pip install .` installs (modified) pix2pixHD, we're relicensing their CC-BY-NC-SA software as Apache 2.0.

At least it would be preferable to depend on it as a library, ideally with the requirements.txt / setup.py mechanism.

**Comment by mjenckel** [comment]
we removed any (modified) pix2pixHD code from the repo and will redirect users to the pix2pixHD github for installation instructions

**Comment by n00blet** [comment]
As pix2pixHD license has been changed to BSD and also from our last meeting we have decided on using pix2pixHD for dewarping.
