### ISSUE TITLE
Why is torch optional?

### ISSUE THREAD

**Issue by kba** [syedsaqibbukhari/docanalysis#21]
`torch` is required for the dewarp script, is it not?

**Comment by n00blet** [comment]
_torch_ and _dominate_ are required for dewarp script at the moment. But those requirements will be removed as from the previous discussion pix2pixHD has a different License. So, we will remove the pix2pixHD code and navigate the users to install pix2pix for dewaping script in the README.

**Comment by n00blet** [comment]
torch and dominate are required by pix2pixHD  dca0cce94cff5aa1cf29e6c51aad7d285d56f1d4
