### ISSUE TITLE
Variable `pix2pixHD_path` is not defined

### ISSUE THREAD

**Issue by kba** [syedsaqibbukhari/docanalysis#28]
In dewarping, introduced in 8058ed17

**Comment by n00blet** [comment]
Hello, Sorry we were making some changes in the **_dev_** branch. Now, **_merger_** branch has been updated and except for dewarping, rest of the scripts are available in OCR-D cli format. Please do check.

And dewarping script will also be changed into OCR-D cli format.

**Comment by n00blet** [comment]
Hello, 
Currently, the dewarping script is not completely according to OCR-D cli format. And we need some clarification from your side regarding additional cli options. And we have also raised an issue in OCD-D core [https://github.com/OCR-D/core/issues/260](url).
And for now, pix2pixHD path is hardcoded for testing purposes and it will be changed in the next commit.

**Comment by kba** [comment]
obsolete now.

**Comment by n00blet** [comment]
what is the **key**: "path" to reference pix2pixHD path in ocrd-json ? ocrd processor throws an exception of 

> Invalid Parameters : pix2pixHD is a required property

AFAIK, we cannot pass it as cli param.

**Comment by kba** [comment]
You can pass a parameter JSON file to the executable, e.g.

```yaml
# params.json
{
   "pix2pixHD": "/home/n00blet/pix2pixHD"
}
```

And run it like

```sh
ocrd-anyocr-dewarp -p params.json ...
```

See https://github.com/OCR-D/core/issues/239 on how to do it without an external file.

**Comment by kba** [comment]
https://ocr-d.github.io/cli#-p---parameter-param_json is the pertinent doc in the spec

**Comment by n00blet** [comment]
Okay, thank you
