### ISSUE TITLE
How to train dewarping?

### ISSUE THREAD

**Issue by kba** [syedsaqibbukhari/docanalysis#31]
How can the dewarping be adapted / how was the model created?

**Comment by mjenckel** [comment]
Currently our dewarping code does not allow for any adaptation / training. We provide a pre-trained model. Details on how the model was trained can be found [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwib_IDju7njAhXFl4sKHZh_A9IQFjAAegQIARAC&url=http%3A%2F%2Fwww.insticc.org%2FPrimoris%2FResources%2FPaperPdf.ashx%3FidPaper%3D73684&usg=AOvVaw17bNbWnRXuNIHWhOARsUrD).
