### ISSUE TITLE
From whence is 'title' imported?

### ISSUE THREAD

**Issue by kba** [syedsaqibbukhari/docanalysis#35]
https://github.com/syedsaqibbukhari/docanalysis/blob/69898d291185e43480945b327ad698bec369feae/ocrd_anybaseocr/cli/ocrd_anybaseocr_binarize.py#L89

**Comment by n00blet** [comment]
_**title(info)**_ has been removed from binarize code in this commit 8667185b10dbb3c8289cfb87c1c0634b2085f8e2.
Some of the missing commits from the pr #33 have been incorporated in this commit. 
In the next commit, we will use ocrd file handlers for the rest of our scripts as mentioned in the previous issue #32
