### ISSUE TITLE
ocrd-tool.json

### ISSUE THREAD

**Issue by kba** [syedsaqibbukhari/docanalysis#5]
Please describe your tools in a file [ocrd-tool.json](https://ocr-d.github.io/ocrd_tool).

**Comment by kba** [comment]
Why was this closed?

**Comment by mjenckel** [comment]
There was an internal misunderstanding from DFKI side, whether the file "ocrd-anybaseocr-parameter.json" already fulfills the requirements of the "ocrd-tools.json".
