### ISSUE TITLE
Status of parameter settings?

### ISSUE THREAD

**Issue by wrznr** [syedsaqibbukhari/docanalysis#7]
The file https://github.com/syedsaqibbukhari/docanalysis/blob/master/ocrd-anyBaseOCR-parameter.json contains parameter settings for the single preprocessing steps. What is their status? Recommendations? Example settings? Required values? Some additional documentation would be highly appreciated! Many thanks!

**Comment by kba** [comment]
c.f. #5

**Comment by mmreza79** [comment]
Updated ocrd-anyBaseOCR-parameter.json file according to ocrd-tool.json format.

**Comment by kba** [comment]
@mmreza79 Please consider #13 as a whole, it is a lot of changes but will make further development much easier than copying parts of my changes piece by piece.

We can also discuss this via Skype or at https://gitter.im/OCR-D/Lobby

**Comment by mmreza79** [comment]
Ok, I will do.
