### ISSUE TITLE
Source code for textlinefinder

### ISSUE THREAD

**Issue by kba** [syedsaqibbukhari/docanalysis#9]
What is the `textlinefinder` ELF binary? Where is it from, how does it work, how is it licensed and where can we study its source code?

**Comment by kba** [comment]
Taken out in https://github.com/syedsaqibbukhari/docanalysis/commit/7d1c681e2c48e6736897b349033db087e78d6939

**Comment by cneud** [comment]
To be replaced with new deep learning dewarping method.

**Comment by kba** [comment]
Was part of dewarping which is obsolete now and will be replaced with deep learning approach
